"use client";

import { useEffect, useState } from "react";

export default function BookingPage({ params }: { params: Promise<{ exhibitionSlug: string; stallId: string }> }) {
  const [ids, setIds] = useState<{ exhibitionSlug: string; stallId: string } | null>(null); const [expiresAt, setExpiresAt] = useState<number | null>(null); const [seconds, setSeconds] = useState(0); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void params.then(setIds); }, [params]);
  useEffect(() => { if (!ids) return; fetch(`/api/public/exhibitions/${ids.exhibitionSlug}/stalls/${ids.stallId}/hold`, { method: "POST" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setExpiresAt(new Date(data.hold.expiresAt).getTime()); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to reserve stall")); }, [ids]);
  useEffect(() => { if (!expiresAt) return; const timer = setInterval(() => setSeconds(Math.max(0, Math.floor((expiresAt - Date.now()) / 1000))), 1000); return () => clearInterval(timer); }, [expiresAt]);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!ids || seconds === 0) return setError("Reservation expired"); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch(`/api/public/exhibitions/${ids.exhibitionSlug}/bookings`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, stallId: ids.stallId }) }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Booking failed"); else setMessage(`Booking ${result.booking.bookingNumber} created successfully.`); }
  return <main className="mx-auto max-w-md px-6 py-12"><p className="text-sm font-medium text-indigo-600">Reserve your space</p><h1 className="mt-2 text-3xl font-semibold">Exhibitor booking</h1>{expiresAt && <p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Your stall is held for {Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, "0")}</p>}{error && <p role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message ? <p className="mt-6 rounded-lg bg-green-50 p-4 text-green-800">{message}</p> : <form onSubmit={submit} className="mt-6 space-y-3"><input name="companyName" required placeholder="Company name" className="w-full rounded-lg border p-3" /><input name="contactPerson" required placeholder="Contact person" className="w-full rounded-lg border p-3" /><input name="email" required type="email" placeholder="Email" className="w-full rounded-lg border p-3" /><input name="phone" placeholder="Phone" className="w-full rounded-lg border p-3" /><textarea name="address" placeholder="Address" className="w-full rounded-lg border p-3" /><button disabled={!expiresAt || seconds === 0} className="w-full rounded-lg bg-indigo-600 p-3 font-medium text-white disabled:opacity-50">Submit booking</button></form>}</main>;
}

