"use client";
import { useEffect, useState } from "react";

export default function SetupPage({ params, searchParams }: { params: Promise<{ exhibitionId: string; hallId: string }>; searchParams: Promise<{ organizationId?: string }> }) {
  const [ids, setIds] = useState<{ exhibitionId: string; hallId: string; organizationId: string }>(); const [status, setStatus] = useState("");
  useEffect(() => { Promise.all([params, searchParams]).then(([route, query]) => setIds({ ...route, organizationId: query.organizationId ?? "" })); }, [params, searchParams]);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!ids?.organizationId) return; setStatus("Uploading to Cloudflare R2…"); const form = new FormData(event.currentTarget); try { const upload = new FormData(); upload.append("file", form.get("file") as File); const assetResponse = await fetch(`/api/organizations/${ids.organizationId}/assets`, { method: "POST", body: upload }); const asset = await assetResponse.json(); if (!assetResponse.ok) throw new Error(asset.error); const response = await fetch(`/api/organizations/${ids.organizationId}/exhibitions/${ids.exhibitionId}/halls/${ids.hallId}/floor-plans`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ canvasWidth: Number(form.get("canvasWidth")), canvasHeight: Number(form.get("canvasHeight")), backgroundAssetId: asset.asset._id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setStatus(`Floor plan version ${data.floorPlan.version} created successfully.`); } catch (error) { setStatus(error instanceof Error ? error.message : "Unable to create floor plan"); } }
  return <main className="mx-auto max-w-2xl px-6 py-12"><p className="text-sm font-medium text-indigo-600">Floor-plan setup</p><h1 className="mt-2 text-3xl font-semibold">Create a hall map</h1><p className="mt-3 text-zinc-500">Upload your floor plan to Cloudflare R2 and define its logical canvas size.</p>{status && <p className="mt-5 rounded-lg bg-zinc-100 p-3 text-sm">{status}</p>}<form onSubmit={submit} className="mt-6 space-y-4 rounded-2xl border bg-white p-6 shadow-sm"><label className="block text-sm font-medium">Floor-plan image or SVG<input name="file" required type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" className="mt-2 block w-full rounded-lg border p-3" /></label><div className="grid grid-cols-2 gap-4"><input name="canvasWidth" required type="number" min="100" defaultValue="1600" placeholder="Canvas width" className="rounded-lg border p-3" /><input name="canvasHeight" required type="number" min="100" defaultValue="2200" placeholder="Canvas height" className="rounded-lg border p-3" /></div><button disabled={!ids?.organizationId} className="w-full rounded-lg bg-indigo-600 p-3 font-medium text-white disabled:opacity-50">Create floor plan</button></form></main>;
}

