"use client";

import { useEffect, useState } from "react";

type Element = { _id: string; type: string; label?: string; status?: string; geometry: { type: "rect"; x: number; y: number; width: number; height: number; rotation?: number }; locked: boolean; visible: boolean; zIndex: number };
type Plan = { _id: string; canvasWidth: number; canvasHeight: number; version: number };

export default function MapEditorPage({ params, searchParams }: { params: Promise<{ exhibitionId: string; hallId: string }>; searchParams: Promise<{ organizationId?: string }> }) {
  const [ids, setIds] = useState<{ exhibitionId: string; hallId: string; organizationId: string } | null>(null);
  const [plan, setPlan] = useState<Plan | null>(null); const [elements, setElements] = useState<Element[]>([]); const [selected, setSelected] = useState<Element | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([params, searchParams]).then(([route, query]) => setIds({ ...route, organizationId: query.organizationId ?? "" })); }, [params, searchParams]);
  useEffect(() => { if (!ids?.organizationId) return; const load = async () => { const halls = await fetch(`/api/organizations/${ids.organizationId}/exhibitions/${ids.exhibitionId}/halls/${ids.hallId}/floor-plans`).then((r) => r.json()); const current = halls.floorPlans?.[0]; if (!current) return; setPlan(current); const data = await fetch(`/api/organizations/${ids.organizationId}/floor-plans/${current._id}/elements`).then((r) => r.json()); setElements(data.elements ?? []); }; void load().catch(() => setError("Unable to load map editor")); }, [ids]);
  async function createElement() { if (!ids || !plan) return; setSaving(true); setError(null); const response = await fetch(`/api/organizations/${ids.organizationId}/floor-plans/${plan._id}/elements`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "STALL", label: `Stall ${elements.length + 1}`, status: "AVAILABLE", geometry: { type: "rect", x: 40 + elements.length * 110, y: 40, width: 90, height: 90 }, locked: false, visible: true, zIndex: 1 }) }); const data = await response.json(); if (!response.ok) setError(data.error ?? "Unable to create element"); else { setElements((current) => [...current, data.element]); setSelected(data.element); } setSaving(false); }
  async function updateElement(patch: Partial<Element>) { if (!ids || !plan || !selected) return; const response = await fetch(`/api/organizations/${ids.organizationId}/floor-plans/${plan._id}/elements/${selected._id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) }); const data = await response.json(); if (!response.ok) return setError(data.error ?? "Unable to save element"); setElements((current) => current.map((item) => item._id === selected._id ? data.element : item)); setSelected(data.element); }
  async function deleteElement() { if (!ids || !plan || !selected) return; const response = await fetch(`/api/organizations/${ids.organizationId}/floor-plans/${plan._id}/elements/${selected._id}`, { method: "DELETE" }); if (!response.ok) return setError("Unable to delete element"); setElements((current) => current.filter((item) => item._id !== selected._id)); setSelected(null); }
  if (!ids || !plan) return <main className="mx-auto max-w-6xl px-6 py-12"><p className="text-zinc-500">Loading map editor…</p></main>;
  return <main className="mx-auto max-w-7xl px-6 py-8"><div className="flex items-center justify-between"><div><p className="text-sm font-medium text-indigo-600">Map editor</p><h1 className="mt-1 text-3xl font-semibold">Floor plan v{plan.version}</h1></div><button onClick={() => void createElement()} disabled={saving} className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">Add stall</button></div>{error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 grid gap-6 lg:grid-cols-[1fr_280px]"><div className="overflow-auto rounded-xl border bg-zinc-100 p-6"><div className="relative bg-white shadow" style={{ width: plan.canvasWidth, height: plan.canvasHeight }}>{elements.map((element) => <button key={element._id} onClick={() => setSelected(element)} className={`absolute rounded border text-xs font-semibold ${selected?._id === element._id ? "z-10 ring-2 ring-indigo-600" : ""}`} style={{ left: element.geometry.x, top: element.geometry.y, width: element.geometry.width, height: element.geometry.height, background: element.type === "STALL" ? "#bbf7d0" : "#dbeafe" }}>{element.label ?? element.type}</button>)}</div></div><aside className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Properties</h2>{!selected ? <p className="mt-3 text-sm text-zinc-500">Select an element to edit it.</p> : <div className="mt-4 space-y-3"><label className="block text-sm">Label<input value={selected.label ?? ""} onChange={(event) => setSelected({ ...selected, label: event.target.value })} onBlur={() => void updateElement({ label: selected.label })} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Type<select value={selected.type} onChange={(event) => void updateElement({ type: event.target.value })} className="mt-1 w-full rounded border p-2"><option>STALL</option><option>ZONE</option><option>ENTRANCE</option><option>EXIT</option><option>STAGE</option><option>WALKWAY</option></select></label><div className="grid grid-cols-2 gap-2">{(["x", "y", "width", "height"] as const).map((key) => <label key={key} className="text-sm">{key}<input type="number" value={selected.geometry[key]} onChange={(event) => setSelected({ ...selected, geometry: { ...selected.geometry, [key]: Number(event.target.value) } })} onBlur={() => void updateElement({ geometry: selected.geometry })} className="mt-1 w-full rounded border p-2" /></label>)}</div><button onClick={() => void deleteElement()} className="w-full rounded border border-red-200 px-3 py-2 text-sm text-red-600">Delete element</button></div>}</aside></div></main>;
}

